name: CI
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: python -m pip install -r requirements.txt
      - run: |
          mike deploy {BRANCH_NAME}
          git push origin HEAD:gh-pages;