name: CI
on:
  push:
env:
  MIKE_BRANCH: gh-pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Setup git config
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Update gh-pages branch
        if: ${{ github.ref_name != env.MIKE_BRANCH }}
        run: |
          mike deploy $(basename $(git rev-parse --abbrev-ref @))
          mike set-default main
          git checkout ${MIKE_BRANCH}
          git push origin HEAD:${MIKE_BRANCH}